status = warn
name = CornerDogs

appender.rolling.type = RollingFile
appender.rolling.name = LOGFILE
appender.rolling.fileName = ./logs/application.log
appender.rolling.filePattern = ./logs/application.log.%d{yyyy-MM-dd}
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d %-5p [%t] %c{1} - %m%n
appender.rolling.policies.type = Policies
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 1
appender.rolling.policies.time.modulate = true

rootLogger.level = info
rootLogger.appenderRef.rolling.ref = LOGFILE

logger.httpclient.name = org.apache.commons.httpclient.HttpMethodBase
logger.httpclient.level = error

logger.spymemcached.name = net.spy.memcached
logger.spymemcached.level = warn
