# Copyright (c) 2024 all9s Solutions
# SPDX-License-Identifier: EPL-2.0

Bundle-Vendor = all9s Solutions
Bundle-Name = all9s Solutions Features

feature.description = all9s Solutions offers Eclipse plug-ins that automate common Java editor tasks, including generated logging statements and code-block ending comments.

feature.copyright = Copyright (c) 2024 all9s Solutions

feature.license.url = https://www.eclipse.org/legal/epl-2.0/
feature.license = This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0, which is available at https://www.eclipse.org/legal/epl-2.0/.
