#
# Copyright (c) 2024 all9s Solutions
# This program and the accompanying materials 
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     Joseph Burris - initial english resources
# 
Bundle-Vendor = all9s Solutions
Bundle-Name = Lumberjack

page.image = /icons/lumberjack.png
category.name = Lumberjack Category
command.name = Lumberjack Command
command.tooltip = Run Lumberjack
command.label = Lumberjack

preferences.page.keywords = logging log lumber lumberjack
preferences.page.title = Lumberjack Preferences
preferences.page.description = Set the default preferences for executing Lumberjack.

preferences.logger_field.label = Logger field
preferences.logger_field.tool_tip = Enter the logger field variable name.
preferences.logger_field.error_message = {0} must be a valid Java identifier.

preferences.label.framework = Logger Framework:
preferences.tool_tip.framework = Select the preferred logging framework to be used for logging generation.
preferences.error.framework = The logging generator could not be instantiated for the selected logging framework.

preferences.label.write_enter = Entering method
preferences.tool_tip.enter_level = Choose the logging level for generating entering statements.
preferences.label.include_params = Include parameters
preferences.label.write_comment = Write Javadoc
preferences.label.write_enter_if = Wrap with conditional

preferences.label.write_exit = Exiting method
preferences.tool_tip.exit_level = Choose the logging level for generating exiting statements.
preferences.label.include_ret_val = Include return value
preferences.label.write_exit_if = Wrap with conditional

preferences.label.write_if_else = if/else statements
preferences.tool_tip.write_if_else = Choose the logging level for generating if/else logging statements.
preferences.label.write_do_while = do/while statements
preferences.tool_tip.write_do_while = Choose the logging level for generating do/while loop logging statements.
preferences.label.write_while = while statements
preferences.tool_tip.write_while = Choose the logging level for generating while loop logging statements.
preferences.label.write_for = for statements
preferences.tool_tip.write_for = Choose the logging level for generating for loop logging statements.
preferences.label.write_try_catch = try/catch statements
preferences.tool_tip.write_try_catch = Choose the logging level for generating try/catch logging statements.
preferences.label.write_synchronized = synchronized statements
preferences.tool_tip.write_synchronized = Choose the logging level for generating synchronized logging statements.
preferences.label.write_variable = variable statements
preferences.tool_tip.write_variable = Choose the logging level for generating variable logging statements.
preferences.label.write_method_call = method call statements
preferences.tool_tip.write_method_call = Choose the logging level for generating method call logging statements.
preferences.label.write_switch = switch statements
preferences.tool_tip.write_switch = Choose the logging level for generating switch logging statements.
