# Copyright (c) 2024 all9s Solutions
# SPDX-License-Identifier: EPL-2.0

# Contributors:
#     Joseph Burris - initial english resources
# 
source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               toc.xml,\
               html/,\
               plugin.properties,\
               ender_context.xml,\
               images/,\
               styles/,\
               build.properties
