# Copyright (c) 2024 all9s Solutions
# SPDX-License-Identifier: EPL-2.0

# Contributors:
#     Joseph Burris - initial english resources
# 
Bundle-Vendor = all9s Solutions
Bundle-Name = Ender

page.image = /icons/end.png
category.name = Ender Category
command.name = Ender Command
command.tooltip = Run Ender
command.label = Ender

preferences.page.keywords = comment comments end ender
preferences.page.message = Select your preferred style for the ending comments:
preferences.page.title = Ender Preferences
preferences.page.description = Set the default preferences for executing Ender.
