# Copyright (c) 2024 all9s Solutions
# SPDX-License-Identifier: EPL-2.0

# Contributors:
#     Joseph Burris - initial english resources
# 
bin.includes = feature.xml,\
               feature.properties,\
               build.properties
